env:
  browser: true
  commonjs: false
  es2021: true
extends:
  - airbnb-base
  - plugin:prettier/recommended
  - plugin:jsdoc/recommended
plugins:
  - prettier
  - require-sort
  - jsdoc
  - disable
overrides:
  - files:
      - '*.js'
    settings:
      disable/plugins:
        - jsdoc
parser: '@babel/eslint-parser'
parserOptions:
  requireConfigFile: false
  babelrc: false
  configFile: false
  ecmaVersion: latest
  sourceType: module
  presets: ['@babel/preset-env']
processor: 'disable/disable'
rules:
  'require-sort/require-sort': [warn, { 'ignoreCase': true }]
  no-param-reassign: ['error', { 'props': false }]
