plugins:
  - stylelint-high-performance-animation
  - stylelint-selector-bem-pattern

extends:
  - '@visionappscz/stylelint-config'
  - '@visionappscz/stylelint-config/order'
  - '@visionappscz/stylelint-config/scss'
  - stylelint-config-recommended-scss

rules:
  indentation: 2
  linebreaks: 'unix'
  unit-allowed-list: ['px', 'rem', '%', 's', 'deg']

  plugin/no-low-performance-animation-properties: true

  plugin/selector-bem-pattern:
    preset: 'bem'
    implicitComponents: '**/c-*.scss'
    componentName: '(([a-z0-9]+(?!-$)-?)+)'
    componentSelectors:
      initial: "\\.{componentName}(((__|--)(([a-z0-9\\[\\]'=]+(?!-$)-?)+))+)?$"
    implicitUtilities: '**/u-*.scss'
    utilitySelectors: "^\\.u-[a-z]+$"

  # Reset for visionapps
  string-quotes: single
  selector-nested-pattern: null
  selector-class-pattern:
